### PR TITLE
chore: replace jest by vitest

### LINKED ISSUE #418: Try Vitest

### PR DESCRIPTION
**Pull request by PascalHelbig**
fix #418 

Todo:
- [ ] test that everything works on Windows

### CODE REVIEW

**Comment by PascalHelbig** [comment]
It is failing on Windows ☹️

**Comment by PascalHelbig** [comment]
I tested it on my machine.
A segmentation fault is creating the problems on Windows:
image

There is an open issue on the vitest repo: https://github.com/vitest-dev/vitest/issues/2045

**Comment by brandonseydel** [comment]
@PascalHelbig - what terminal are you using? powershell/bash/cmd?

**Comment by PascalHelbig** [comment]
> @PascalHelbig - what terminal are you using? powershell/bash/cmd?

@brandonseydel 
I have the problem on bash and cmd. I haven't tried powershell yet.
But only on bash I can see the segmentation fault error message.

**Comment by PascalHelbig** [comment]
In the meantime, we have moved to a monorepo.
This results in many merge conflicts here. If we want to switch to Vitest, we should rebuild the PR again.

**Pull request closed without merging**
